version: '3'
services:
  # MongoDB
  mongodb:
    image: mongo:7 
    container_name: my_mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017" 
    environment:                          # Variables d'entorn    
      MONGO_INITDB_ROOT_USERNAME: root    # Usuari
      MONGO_INITDB_ROOT_PASSWORD: example # Contrasenya

volumes:
  mongodb_data: